platform :ios, '9.0'
project 'Example'
workspace '../CurrencyText'

target 'Example' do
  use_frameworks!

  pod 'CurrencyText', :path => '../'  

  target 'ExampleTests' do
    inherit! :search_paths
  end

end
