platform :ios, '9.0'
workspace '../CurrencyText'

target 'CurrencyTextDemo' do
  use_frameworks!

  pod 'CurrencyText', :path => '../'  

  target 'CurrencyTextDemoTests' do
    inherit! :search_paths
  end

end
