
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
    	clean: true, code_coverage: true, scheme: "UICurrencyTextFieldDemo", devices: ["iPhone SE", "iPhone 8"]
    )
  end
end
